/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgsdatacontainer.h
 *
 * DESCRIPTION.: This file is used to define the version of libgsdatacontainer
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2004/0/19 @ 22:31
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1462

#ifdef DEFVER_LIBGSDATACONTAINER
#define VERSION_LIBGSDATACONTAINER 1462
#endif //DEFVER_LIBGSDATACONTAINER
