/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgschat.h
 *
 * DESCRIPTION.: This file is used to define the version of libgschat
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2004/0/19 @ 21:15
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1463

#ifdef DEFVER_LIBGSCHAT
#define VERSION_LIBGSCHAT 1463
#endif //DEFVER_LIBGSCHAT
