/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgssocket.h
 *
 * DESCRIPTION.: This file is used to define the version of libgssocket
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2004/0/20 @ 11:41
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1454

#ifdef DEFVER_LIBGSSOCKET
#define VERSION_LIBGSSOCKET 1454
#endif //DEFVER_LIBGSSOCKET
