/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgsscore.h
 *
 * DESCRIPTION.: This file is used to define the version of libgsscore
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2003/3/29 @ 22:50
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1245

#ifdef DEFVER_LIBGSSCORE
#define VERSION_LIBGSSCORE 1245
#endif //DEFVER_LIBGSSCORE
