/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgsmsclient.h
 *
 * DESCRIPTION.: This file is used to define the version of libgsmsclient
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2004/0/19 @ 22:42
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1429

#ifdef DEFVER_LIBGSMSCLIENT
#define VERSION_LIBGSMSCLIENT 1429
#endif //DEFVER_LIBGSMSCLIENT
