/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgsthreads.h
 *
 * DESCRIPTION.: This file is used to define the version of libgsthreads
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2004/0/19 @ 23:41
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1447

#ifdef DEFVER_LIBGSTHREADS
#define VERSION_LIBGSTHREADS 1447
#endif //DEFVER_LIBGSTHREADS
