/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgscsp.h
 *
 * DESCRIPTION.: This file is used to define the version of libgscsp
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2004/0/19 @ 22:27
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1456

#ifdef DEFVER_LIBGSCSP
#define VERSION_LIBGSCSP 1456
#endif //DEFVER_LIBGSCSP
