/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgsproxyclient.h
 *
 * DESCRIPTION.: This file is used to define the version of libgsproxyclient
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2004/0/19 @ 23:27
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1451

#ifdef DEFVER_LIBGSPROXYCLIENT
#define VERSION_LIBGSPROXYCLIENT 1451
#endif //DEFVER_LIBGSPROXYCLIENT
