/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgsclinkc.h
 *
 * DESCRIPTION.: This file is used to define the version of libgsclinkc
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2002/4/16 @ 13:47
 * AUTHOR......: gplante
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1040

#ifdef DEFVER_LIBGSCLINKC
#define VERSION_LIBGSCLINKC 1040
#endif //DEFVER_LIBGSCLINKC
