/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgslauncher.h
 *
 * DESCRIPTION.: This file is used to define the version of libgslauncher
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2003/3/30 @ 23:5
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1276

#ifdef DEFVER_LIBGSLAUNCHER
#define VERSION_LIBGSLAUNCHER 1276
#endif //DEFVER_LIBGSLAUNCHER
