/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgsconnect.h
 *
 * DESCRIPTION.: This file is used to define the version of libgsconnect
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2004/0/19 @ 23:20
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1451

#ifdef DEFVER_LIBGSCONNECT
#define VERSION_LIBGSCONNECT 1451
#endif //DEFVER_LIBGSCONNECT
