/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgslobbylan.h
 *
 * DESCRIPTION.: This file is used to define the version of libgslobbylan
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2003/3/29 @ 22:27
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1276

#ifdef DEFVER_LIBGSLOBBYLAN
#define VERSION_LIBGSLOBBYLAN 1276
#endif //DEFVER_LIBGSLOBBYLAN
