/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgscrypto.h
 *
 * DESCRIPTION.: This file is used to define the version of libgscrypto
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2004/0/19 @ 23:25
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1421

#ifdef DEFVER_LIBGSCRYPTO
#define VERSION_LIBGSCRYPTO 1421
#endif //DEFVER_LIBGSCRYPTO
