/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgsadmin.h
 *
 * DESCRIPTION.: This file is used to define the version of libgsadmin
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2004/0/19 @ 23:2
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1450

#ifdef DEFVER_LIBGSADMIN
#define VERSION_LIBGSADMIN 1450
#endif //DEFVER_LIBGSADMIN
