/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgscdkey.h
 *
 * DESCRIPTION.: This file is used to define the version of libgscdkey
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2004/0/19 @ 21:11
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1395

#ifdef DEFVER_LIBGSCDKEY
#define VERSION_LIBGSCDKEY 1395
#endif //DEFVER_LIBGSCDKEY
