/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgsgamestarter.h
 *
 * DESCRIPTION.: This file is used to define the version of libgsgamestarter
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2003/3/29 @ 22:18
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1278

#ifdef DEFVER_LIBGSGAMESTARTER
#define VERSION_LIBGSGAMESTARTER 1278
#endif //DEFVER_LIBGSGAMESTARTER
