/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgsclinkg.h
 *
 * DESCRIPTION.: This file is used to define the version of libgsclinkg
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2002/4/16 @ 13:49
 * AUTHOR......: gplante
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1040

#ifdef DEFVER_LIBGSCLINKG
#define VERSION_LIBGSCLINKG 1040
#endif //DEFVER_LIBGSCLINKG
