/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgsregserver.h
 *
 * DESCRIPTION.: This file is used to define the version of libgsregserver
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2004/0/19 @ 22:59
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1413

#ifdef DEFVER_LIBGSREGSERVER
#define VERSION_LIBGSREGSERVER 1413
#endif //DEFVER_LIBGSREGSERVER
