/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgsclient.h
 *
 * DESCRIPTION.: This file is used to define the version of libgsclient
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2004/0/19 @ 22:26
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1454

#ifdef DEFVER_LIBGSCLIENT
#define VERSION_LIBGSCLIENT 1454
#endif //DEFVER_LIBGSCLIENT
