/***SDOF***********************************************************************
 *
 *                           UbiSoft Development Network
 *                           ---------------------------
 *
 * FILE........: version_libgsgame.h
 *
 * DESCRIPTION.: This file is used to define the version of libgsgame
 *               This file was generated by a script for version management. 
 *               If you have problems with this file, you should contact 
 *               Guillaume Plante at gplante.com.
 *
 ******************************************************************************
 *                                  FILE HISTORY
 ******************************************************************************
 *
 * DATE........: 2003/3/29 @ 22:16
 * AUTHOR......: gscompile
 * DESCRIPTION.: Automatic generation
 *
 ***********************************************************************EDOF***/
//_LAST_VERSION=1279

#ifdef DEFVER_LIBGSGAME
#define VERSION_LIBGSGAME 1279
#endif //DEFVER_LIBGSGAME
