//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CryEdit.rc
//
#define IDC_SELECTOBJECTS               2
#define IDC_REMOVE                      3
#define ID_IMPORT                       3
#define IDB_MAIL                        3
#define IDOK2                           3
#define ID_RECOMPILE_CHANGES            3
#define IDC_CHECKOUT                    3
#define IDC_COPY                        3
#define ID_EXPORT                       4
#define IDC_PLACE                       4
#define IDC_PAINT                       4
#define IDCANCEL3                       4
#define ID_RECOMPILE_SELECTION          4
#define IDC_ADD_CGF                     5
#define ID_RECOMPILE_SELECTION2         5
#define ID_CANCEL                       5
#define IDC_GEN_PREVIEW                 6
#define IDC_CLONE_CGF                   6
#define ID_RECOMPILE_CHANGES2           6
#define IDC_INVERSE_USE                 7
#define IDC_USE_NONE                    8
#define IDC_USE_ALL                     9
#define IDD_ABOUTBOX                    100
#define IDC_EDIT                        101
#define IDD_CRITICAL_ERROR              101
#define ID_INFODLG_UPDATE               102
#define IDB_LIGHTBULB                   102
#define IDC_EDIT2                       102
#define IDC_SAVE                        102
#define IDC_FILE                        102
#define IDD_PREFERENCES                 102
#define IDD_DIALOGBAR                   103
#define IDC_ROLLUPTAB                   103
#define IDEDIT_TextEdit                 104
#define CG_IDS_TIPOFTHEDAY              104
#define IDD_TOOLSCONFIG                 104
#define IDC_POINTER                     104
#define IDDIALOG_TextScroller           105
#define CG_IDS_TIPOFTHEDAYMENU          105
#define IDC_POINTER_COPY                105
#define IDC_CONSOLEEDIT                 106
#define CG_IDS_DIDYOUKNOW               106
#define IDC_NODROP                      106
#define CG_IDS_FILE_ABSENT              107
#define CG_IDS_FILE_CORRUPT             108
#define CG_IDS_TIPOFTHEDAYHELP          109
#define IDD_TRACKVIEWDIALOG             110
#define IDC_SEQUENCES                   111
#define ID_TOOL1                        114
#define ID_TOOL2                        115
#define ID_TOOL3                        116
#define ID_TOOL4                        117
#define ID_TOOL5                        118
#define ID_TOOL6                        119
#define ID_TOOL7                        120
#define ID_TOOL8                        121
#define ID_TOOL9                        122
#define ID_TOOL10                       123
#define ID_TOOL11                       124
#define ID_TOOL12                       125
#define ID_TOOL13                       126
#define ID_TOOL14                       127
#define IDR_MAINFRAME                   128
#define ID_TOOL15                       128
#define IDR_CRYEDITYPE                  129
#define IDS_WEAPONS                     129
#define ID_TOOL16                       129
#define IDD_FILE_BROWSER                129
#define IDR_ANIMATION                   130
#define IDD_EDIT_ACCELMAP               130
#define ID_TOOL17                       130
#define IDS_TOOLSCONFIG                 130
#define ID_TOOL18                       131
#define ID_TOOL19                       132
#define ID_TOOL20                       133
#define ID_TOOL21                       134
#define ID_TOOL22                       135
#define ID_TOOL23                       136
#define ID_TOOL24                       137
#define ID_TOOL25                       138
#define ID_TOOL26                       139
#define ID_TOOL27                       140
#define ID_TOOL28                       141
#define IDR_VIEW_OPTIONS                142
#define ID_TOOL29                       142
#define ID_TOOL30                       143
#define ID_DB_MAKE_FROM_SELECTION       145
#define IDC_METHODS_FRAME               147
#define IDD_MISSIONMAINPROPS            153
#define IDB_CAMERA                      154
#define IDD_TERRAIN                     156
#define IDR_TERRAIN                     157
#define IDC_STATIC1                     158
#define IDR_BRUSHES                     159
#define IDD_SKY                         161
#define IDR_SKY                         162
#define IDR_VIEW                        163
#define IDC_HAND_INTERNAL               165
#define IDB_BRUSH                       166
#define IDD_SIZE                        167
#define IDD_GENERATION                  168
#define IDD_LIGHTING                    169
#define IDD_TERRAIN_TEXTURE             170
#define IDC_NEXTTIP                     170
#define IDD_STRING                      171
#define IDC_STARTUP                     171
#define IDR_LAYER                       172
#define IDC_TIPSTRING                   172
#define IDR_LIGHTMAP                    175
#define IDB_WATER                       179
#define IDD_DIMENSIONS                  180
#define IDD_WATERLEVEL                  181
#define IDD_FOG                         182
#define IDD_LOADING                     183
#define IDC_STATICOBJ                   192
#define IDD_STARTUP                     194
#define IDD_SELECT_FILE                 195
#define IDB_TREE_VIEW                   196
#define IDD_SELECT_OBJECT               197
#define IDD_SET_HEIGHT                  198
#define IDB_COLORS                      199
#define IDC_LIST_OPTIONS                200
#define IDC_WORKSPACE                   201
#define IDB_PREFERENCES                 202
#define IDC_ZOOM_INTERNAL               204
#define IDD_TIP                         204
#define IDC_BRUSH_INTERNAL              205
#define IDR_CGF                         206
#define IDD_ROLLUP                      209
#define IDD_MAINTOOLS                   210
#define IDC_ARRBLCK                     217
#define IDC_ARRBLCKCROSS                218
#define IDC_ARRWHITE                    219
#define IDD_TERRAIN_CURVE               220
#define IDD_TERRAIN_TOOLS               221
#define IDD_TERRAIN_PANEL               221
#define IDR_EDIT_MODE                   222
#define IDD_MODELVIEW_PANEL             222
#define IDD_OBJECT_PANEL                223
#define IDR_OBJECT_MODIFY               223
#define IDD_NUMBER                      224
#define IDD_INFO_PANEL                  225
#define IDI_UP_ARROW                    226
#define IDD_PANEL_STATICOBJ             226
#define IDI_DOWN_ARROW                  227
#define IDD_DIALOG1                     227
#define IDD_OBJTYPE_BROWSER             229
#define IDD_INFO_BAR                    230
#define IDD_STARTUP_LOGO                231
#define IDB_CRYTEK_LOGO                 233
#define IDD_TERRAIN_FORMULA             234
#define IDB_TREE_VIEW1                  234
#define IDD_SURFACE_TYPES               236
#define IDD_PANEL_TREEBROWER            237
#define IDD_PANEL_PROPERTIES            238
#define IDD_PROPERTIES                  239
#define IDB_TABPANEL                    244
#define IDD_EXCEPTION                   245
#define IDD_PANEL_VOLUME                246
#define IDD_PANEL_DISPLAY_HIDE          247
#define IDR_GAMEACCELERATOR             248
#define IDD_PANEL_DISPLAY_RENDER        248
#define IDD_CONSOLE                     249
#define IDD_SHADERS                     250
#define IDD_PANEL_BUILDING              251
#define IDD_PANEL_ENTITY                252
#define IDD_FILE_DIALOG                 254
#define IDD_MISSIONS                    255
#define IDR_MISSION_BAR                 256
#define IDD_PANEL_BUILDING1             257
#define IDR_LAYERS_BAR                  257
#define IDD_PANEL_TERRAIN_MODIFY        258
#define IDR_TRACKVIEW                   258
#define IDD_PANEL_TERRAIN_HOLE          259
#define IDB_LOCK_SELECTION_UP           262
#define IDB_LOCK_SELECTION_DOWN         263
#define IDB_LOCK_SELECTION_FOCUS        264
#define IDB_LOCK_SELECTION_DISABLE      265
#define IDB_ENTITY_EVENTS_TREE          266
#define IDD_DIALOG2                     267
#define IDD_CHOOSE_COLOR                269
#define IDD_PANEL_SOUNDOBJECT           270
#define IDC_COLOR_PICKER                271
#define IDD_PANEL_VEGETATION            271
#define IDB_PICK_COLOR                  272
#define IDD_INFO_BAR_HOLDER             272
#define IDC_HAND_INTERNAL1              272
#define IDC_HIT_CURSOR                  272
#define IDC_ARROW_ADDKEY                273
#define IDB_SPLASH                      275
#define IDD_UNDO_DROPDOWN               276
#define IDD_PANEL_ENVIRONMENT           277
#define IDD_PANEL_SHADERTEMPLATE        278
#define IDD_PANEL_TEXTURE_TOOL          279
#define IDD_INFO_PROGRESS_BAR           280
#define IDD_PANEL_VEGETATION_OBJECTS    281
#define IDD_PANEL_SA                    282
#define IDD_PANEL_PICKENTITIES          282
#define IDD_WEAPONS                     283
#define IDI_ICONSMALL                   292
#define IDI_SMALLICON                   292
#define ID_RESOURCES_GENERATECGFTHUMBNAILS 293
#define IDD_AICONFIG                    296
#define IDD_PANEL_DISPLAY_LAYERS        297
#define IDD_LAYERS_SELECT               298
#define IDI_PLUS                        299
#define IDI_MINUS                       300
#define ID_AI_GENERATETRIANGULATION     303
#define ID_FILE_NEW304                  304
#define IDI_DELETE                      305
#define IDI_NEW                         308
#define IDB_LAYER_BUTTONS               309
#define IDI_LAYERS                      310
#define IDB_TRACKVIEW_KEYS              310
#define IDI_EXPORT                      311
#define IDB_TRACKVIEW_NODES             311
#define IDI_IMPORT                      312
#define IDB_PROPERTIES                  312
#define IDI_LOCK                        313
#define IDC_CURSOR1                     313
#define IDB_VEGETATION_TREE             313
#define IDI_TERRAIN_COLLISION           314
#define IDD_TV_TCBKEY                   314
#define IDB_VEGETATION_TREE_STATE       314
#define IDD_PANEL_AIPOINT               315
#define ID_RESOURCES_REDUCEWORKINGSET   315
#define IDI_GRID                        315
#define IDI_CLONE                       316
#define IDD_TV_SEQ_PROPS                317
#define IDI_REPLACE                     317
#define IDD_TV_ENTITY_KEY               318
#define ID_TOOLS_GENERATELIGHTMAPS      318
#define IDI_RENAME                      318
#define IDD_TV_TRACK_PROPS              319
#define ID_TOOLS_RELOADINDOORS          319
#define IDD_DIALOG3                     320
#define IDD_NEW_LEVEL                   320
#define IDC_LEFTRIGHT                   321
#define IDD_EQUIPPACKS                  321
#define ID_TOOLS_EQUIPPACKSEDIT         322
#define IDD_TV_TCBKEY1                  322
#define IDD_TV_SELKEY                   322
#define IDC_POINTER_OBJHIT              322
#define ID_EDIT_REDO323                 323
#define IDC_POINTER_LINK                323
#define ID_EDIT_HIDE                    324
#define IDC_POINTER_LINKNOW             324
#define ID_EDIT_UNHIDEALL               325
#define ID_EDIT_FREEZE                  326
#define ID_EDIT_UNFREEZEALL             327
#define ID_RELOAD_TERRAIN               328
#define IDD_GRID_SETTINGS               330
#define ID_VIEW_RENDERINWIREFRAME       331
#define IDD_TV_SOUNDKEY                 331
#define ID_VIEW_SNAPTOGRID              332
#define IDD_TV_CHARACTER_KEY            332
#define ID_VIEW_GRIDSETTINGS            333
#define IDD_AICHARACTERS                333
#define ID_VIEW_XPLOOK                  335
#define IDB_MARKER                      336
#define IDR_TERRAIN_BAR                 339
#define IDD_LAYOUT                      341
#define IDB_LAYOUTS                     342
#define ID_VIEW_CONFIGURELAYOUT         343
#define ID_VIEW_A                       344
#define IDD_OBJECT_BROWSER              345
#define IDB_OBJECTS_BROWSER             346
#define IDD_SOUNDPRESETS                348
#define ID_SOUND_PRESETS                349
#define IDR_SOUNDPRESETS                350
#define IDD_DIALOG4                     352
#define IDD_SELECTSOUNDPRESET           352
#define IDD_SELECTPRESET                352
#define IDD_PANEL_SS                    353
#define IDD_PANEL_SHAPE                 353
#define IDD_PANEL_TERRAIN_MODIFY1       354
#define IDD_PANEL_TERRAINLAYER          354
#define IDD_PANEL_TERRAIN_LAYER         354
#define IDD_PANEL_SHAPE1                355
#define IDD_PANEL_BRUSH                 355
#define IDI_FILE_BROWSE                 361
#define ID_EDIT_LOCKSELECTION           362
#define ID_VIEW_ENABLEPHYSICS           363
#define ID_VIEW_VIEWUNDERTERRAIN        364
#define ID_TOOLS_LOGMEMORYUSAGE         365
#define ID_TERRAIN_EXPORTBLOCK          366
#define ID_TERRAIN_IMPORTBLOCK          367
#define ID_TOOLS_CONFIGURETOOLS         368
#define ID_TOOLS_S                      369
#define ID_TOOLS_TOOL1                  370
#define ID_TOOLS_CUSTOMIZEKEYBOARD      371
#define ID_EXPORT_INDOORS               372
#define ID_EDIT_ALIGNOBJECT             373
#define ID_ALIGNOBJECT_ALIGNTOGRID      374
#define ID_ALIGNOBJECT_ALIGNTTOOBJECT   375
#define ID_GAME_FD                      376
#define ID_VIEW_CYCLE2DVIEWPORT         377
#define ID_SNAPANGLE                    378
#define ID_EDIT_ROTATESELECTION         379
#define ID_ROTATESELECTION_XAXIS        380
#define ID_ROTATESELECTION_YAXIS        381
#define ID_ROTATESELECTION_ZAXIS        382
#define ID_ROTATESELECTION_ROTATEANGLE  383
#define ID_EDIT_CONVERTSELECTION        384
#define ID_CONVERTSELECTION_TOBRUSHES   385
#define ID_CONVERTSELECTION_TOSTATICENTITY 386
#define ID_EDIT_RENAMEOBJECT            387
#define ID_EDIT_RENAMEOBJECT388         388
#define IDD_DATABASE                    389
#define IDR_ENTITY_PROTOTYPE            390
#define IDR_DB_ENTITY_BAR               390
#define IDR_DB_MATERIAL_BAR             391
#define ID_FILE_EXPORTVISIBLEOBJECTS    392
#define IDB_MATERIAL_TREE               392
#define IDD_CHOOSEENTITY                393
#define IDD_SELECT_ENTITY_CLASS         393
#define IDR_EAXPRESETS                  393
#define IDD_STRING_GROUP                394
#define IDR_DB_ENTITY                   395
#define ID_LIBRARY_ADD                  396
#define ID_LIBRARY_REMOVE               397
#define IDD_DIALOG5                     398
#define IDD_DB_ENTITY                   398
#define ID_ENTITYPROTOTYPE_ADDNEWPROTOTYPE 399
#define IDD_PANEL_ENTITY1               399
#define IDD_DB_ENTITY_METHODS           399
#define ID_ENTITY_RELOAD                401
#define ID_ENTITYPROTOTYPE_UPDATEALL    402
#define ID_ENTITY_RELOAD403             403
#define ID_Menu                         404
#define ID_UIELEMENTS_DATABASEVIEW      406
#define ID_Menu407                      407
#define ID_Menu408                      408
#define ID_EDIT_NEXTSELECTIONMASK       410
#define IDD_DIALOG6                     411
#define IDD_AIANCHORS                   411
#define IDD_TV_EXPRKEY                  412
#define ID_ENTITYPROTOTYPE_CUT          413
#define IDD_LM_COMPILER                 417
#define IDD_MUSICINFO                   418
#define ID_Menu419                      419
#define IDD_EAXPRESETS                  419
#define ID_SOUND_SHOWMUSICINFO          420
#define IDD_PANEL_PREVIEW               420
#define ID_EAX_PRESETS                  421
#define IDD_SOURCESAFESETTINGS          421
#define ID_OBJECT_LINK                  422
#define IDD_CHECKOUT                    422
#define ID_OBJECT_UNLINK                423
#define IDD_LAYER_PROPS                 423
#define ID_EDIT_MODE                    424
#define IDD_ERROR_REPORT                424
#define ID_MODE_SELECTMODE              425
#define IDD_TV_CONSOLE_KEY              425
#define ID_MODE_BRUSH                   426
#define IDD_DYNAMIC_HELP                426
#define ID_EDIT_TRANSFORMATION          427
#define IDD_TV_MOVIEKEY                 427
#define IDD_TV_MUSICKEY                 427
#define ID_TRANSFORMATION_CONSTRAINTOXAXIS 428
#define IDD_MODELVIEW_MULTIPART         428
#define ID_MODIFY_GOTOSELECTION         429
#define IDD_PANEL_PREFAB                429
#define ID_MODIFY_SETHEIGHT             430
#define ID_VIEW_TAGLOCATION             431
#define ID_TAGLOCATION_TAG1             432
#define ID_TAGLOCATION_TAG2             433
#define ID_TAGLOCATION_TAG3             434
#define ID_TAGLOCATION_TAG4             435
#define ID_TAGLOCATION_TAG5             436
#define ID_TAGLOCATION_TAG6             437
#define ID_TAGLOCATION_LOCATION7        438
#define ID_TAGLOCATION_LOCATION8        439
#define ID_TAGLOCATION_LOCATION9        440
#define ID_TAGLOCATION_LOCATION10       441
#define ID_TAGLOCATION_LOCATION11       442
#define ID_TAGLOCATION_LOCATION12       443
#define ID_DISPLAY_GOTOLOCATION         444
#define ID_DISPLAY_CHANGEFLYSPEED       445
#define ID_CHANGEMOVESPEED_INCREASE     446
#define ID_CHANGEMOVESPEED_DECREASE     447
#define ID_CHANGEMOVESPEED_CHANGESTEP   448
#define ID_MODIFY_SEP                   449
#define ID_MODIFY_AIPOINT_PICKLINK      450
#define ID_Menu451                      451
#define ID_MODIFY_SEP452                452
#define ID_CONVERTSELECTION_TOSIMPLEENTITY 453
#define ID_GAME_UPDATELIGHTMAPSONSELECTION 454
#define ID_GAME_SEP                     455
#define ID_MODIFY_SEP458                458
#define ID_MODIFY_MATERIAL              459
#define ID_MATERIAL_ASSIGNCURRENT       460
#define ID_MATERIAL_RESETTODEFAULT      461
#define ID_MATERIAL_GETMATERIAL         462
#define ID_TOOLS_UPDATELIGHTMAPS        463
#define ID_MODIFY_PHYSICS               464
#define ID_PHYSICS_GETPHYSICSSTATE      465
#define ID_PHYSICS_RESETPHYSICSSTATE    466
#define ID_TOOLS_CONFIGURESOURCESAFE    467
#define ID_FILE_SOURCESAFESETTINGS      468
#define ID_FILE_SEP                     469
#define IDI_QUESTIONMARK                472
#define IDI_FILEOPEN_BACK               473
#define IDR_PANEL_LAYERS                474
#define IDI_FILEOPEN_UP                 474
#define IDR_PANEL_VEGETATION            475
#define ID_GAME_SYNCPLAYER              476
#define IDR_DYNAMIC_HELP                476
#define IDR_DB_MUSIC_BAR                477
#define IDR_DB_PREFAB_BAR               478
#define IDB_SELECT_OBJECT_LIST          479
#define IDB_ERROR_REPORT                480
#define ID_FILE_SAVELEVELRESOURCES      480
#define ID_VALIDATELEVEL                481
#define ID_HELP_DYNAMICHELP             482
#define ID_FILE_CHANGEMOD               483
#define ID_FILE_SEP484                  484
#define IDB_BITMAP2                     485
#define IDB_FILES_IMAGE                 485
#define IDB_MATERIAL_TREE1              486
#define IDB_MUSIC_TREE                  486
#define IDB_SOUND_FILES                 487
#define IDI_FOLDER                      488
#define IDB_MATERIAL_TREE2              488
#define IDB_PREFABS_TREE                488
#define ID_TERRAIN_RESIZETERRAIN        489
#define IDB_MATERIAL_TREE3              489
#define IDB_PARTICLES_TREE              489
#define IDC_POINTER_OBJECT_ROTATE       494
#define IDC_POINTER_OBJECT_SCALE        495
#define IDC_POINTER_OBJECT_MOVE         496
#define IDC_POINTER_PLUS                498
#define IDB_BITMAP1                     498
#define IDB_ENTITY_TREE                 498
#define IDC_POINTER_MINUS               499
#define IDR_AVI_RECORDER_BAR            499
#define IDC_POINTER_GET_HEIGHT          500
#define IDC_POINTER_FLATTEN             501
#define IDC_POINTER_FLATTEN1            502
#define IDC_POINTER_SMOOTH              502
#define IDC_HEIGHTMAP_BORDER            1000
#define IDC_COMMANDS                    1000
#define IDC_EDIT_LIST                   1000
#define IDC_TERRAIN_SIZE                1001
#define IDC_CALLSTACK                   1001
#define IDC_GEN_STATUS                  1002
#define IDC_EXCEPTION_CODE              1002
#define IDC_TERRAIN                     1003
#define IDC_PASSES                      1003
#define IDC_EXCEPTION_ADDRESS           1003
#define IDC_SKY                         1004
#define IDC_FREQUENCY                   1004
#define IDC_EXCEPTION_MODULE            1004
#define IDC_CURRENTS                    1004
#define IDC_MATERIALS                   1005
#define IDC_FADE                        1005
#define IDC_EXCEPTION_DESC              1005
#define IDC_ASSIGN                      1005
#define ID_RELOAD_TEXTURES              1005
#define IDC_TXT_EDIT1                   1005
#define IDC_LIBRARY                     1006
#define IDC_FREQSTEP                    1006
#define IDC_ERROR_TEXT                  1006
#define IDC_RAND                        1007
#define IDC_RESET                       1007
#define IDC_COVER                       1008
#define IDB_EXIT                        1008
#define IDC_SHARPNESS                   1009
#define IDB_SAVE                        1009
#define IDC_ALREADY_AFFECTED            1009
#define IDC_FILELIST                    1009
#define IDC_PASSES_NUM                  1010
#define IDC_LOOKIN                      1010
#define IDC_FREQUENCY_NUM               1011
#define IDC_BACK                        1011
#define IDC_FADE_NUM                    1012
#define IDC_SHORTCUTS                   1012
#define IDC_FREQSTEP_NUM                1013
#define IDC_EDIT_KEY                    1013
#define IDC_HISTORY                     1013
#define IDC_RAND_NUM                    1014
#define IDC_UP                          1014
#define IDC_COVER_NUM                   1015
#define IDC_FILESTYPE                   1015
#define IDC_SHARPNESS_NUM               1016
#define IDC_FILEINFO                    1016
#define IDC_PROCESS_OBJECTS             1017
#define IDC_BLUR                        1017
#define IDC_AMBIENT_BRIGHTNESS          1018
#define IDC_BLUR_NUM                    1018
#define IDC_BRIGHTNESS                  1019
#define IDC_SUNHEIGHT                   1019
#define IDC_GENERATE                    1020
#define IDC_STATUS                      1021
#define IDC_LAYER_LIST                  1022
#define IDC_SUNBRIGHTNESS               1022
#define IDC_SHADOWBRIGHTNESS            1023
#define IDC_MOVE_UP                     1024
#define IDC_LIGHTINGCONTRAST            1024
#define IDC_MOVE_DOWN                   1025
#define IDC_SUN_DIRECTION               1025
#define IDC_GENERATE_PREVIEW            1026
#define IDC_SUN_HEIGHT                  1026
#define IDC_ADD_LAYER                   1027
#define IDC_SHADOW_INTENSITY            1027
#define IDC_LAYER_START_END             1028
#define IDC_AMBIENT                     1028
#define IDC_SEL_START                   1029
#define IDC_SHADOW_BLUR                 1029
#define IDC_REMOVE_LAYER                1030
#define IDC_LOAD_TEXTURE                1031
#define IDC_SEL_END                     1032
#define IDC_SEL_START_END_NUM           1033
#define IDC_RENAME_LAYER                1034
#define IDC_LAYER_OPT_FRAME             1035
#define IDC_LAYER_TEX_INFO              1036
#define IDC_LAYER_TEX_PREVIEW           1037
#define IDC_STRING                      1038
#define IDC_LAYER_SLOPE                 1038
#define IDC_LAYER_MASK_PREVIEW          1039
#define IDC_GROUP                       1039
#define IDC_FINAL_TEX_PREVIEW           1040
#define IDC_SLOPE_SEL_START             1041
#define IDC_SLOPE_SEL_MIN_MAX_NUM       1042
#define IDC_SLOPE_SEL_END               1043
#define IDC_CAPTION1                    1044
#define IDC_CAPTION2                    1045
#define IDC_EXPORT                      1047
#define IDC_IMPORT                      1048
#define IDC_IMPORT_MAP                  1049
#define IDC_SCALE                       1049
#define IDC_512                         1050
#define IDC_ADD_SFTYPE                  1050
#define IDC_EXPORT_MAP                  1050
#define IDC_1024                        1051
#define IDC_REMOVE_SFTYPE               1051
#define IDC_2048                        1052
#define IDC_RENAME_SFTYPE               1052
#define IDC_4096                        1053
#define IDC_ADD_DETAILOBJECT            1053
#define IDC_HEIGHTSLIDER                1054
#define IDC_REMOVE_DETAILOBJECT         1054
#define IDC_8192                        1054
#define IDC_LEVELNUM                    1055
#define IDC_CLONE_SFTYPE                1055
#define IDC_8193                        1055
#define IDC_SHADOWS                     1057
#define IDC_TERRAINSHADOWS              1057
#define IDC_LIGHTING                    1058
#define IDC_TEXTURED                    1058
#define IDC_SMOOTH                      1059
#define IDC_RADIO1                      1059
#define IDC_LINEAR                      1059
#define IDC_CREATE_NEW                  1059
#define IDC_ADD_TO_MAP                  1059
#define ID_INSERT_ENTITY                1059
#define IDC_FILL_MODE                   1059
#define IDC_VISIBLE                     1059
#define IDC_HOLE_MAKE                   1059
#define IDC_ZAXIS                       1059
#define IDC_WAYPOINT                    1059
#define IDC_CONSTANT                    1059
#define IDC_ORT_ONCE                    1059
#define IDC_SHADOWS2                    1059
#define IDC_OBJECTSHADOWS               1059
#define IDC_SELMOOD                     1059
#define IDC_3D                          1059
#define IDC_RADIO2                      1060
#define IDC_EXP                         1060
#define IDC_OPEN_RECENT                 1060
#define IDC_REMOVE_FROM_MAP             1060
#define IDC_WIREFRAME_MODE              1060
#define IDC_HIDDEN                      1060
#define IDC_REPLACE                     1060
#define IDC_XAXIS                       1060
#define IDC_HIDEPOINT                   1060
#define IDC_CYCLE                       1060
#define IDC_ORT_CONSTANT                1060
#define IDC_VOLRAMP                     1060
#define IDC_STEREO                      1060
#define IDC_RADIO3                      1061
#define IDC_EXP2                        1061
#define IDC_OPEN_MAP                    1061
#define IDC_FROZEN                      1061
#define IDC_YAXIS                       1061
#define IDC_ENTRYPOINT                  1061
#define IDC_ORT_LOOP                    1061
#define IDC_DP4                         1061
#define IDC_SLIDER1                     1062
#define IDC_DENSITY                     1062
#define IDC_ALTITUDE                    1062
#define IDC_BRUSH_RADIUS_SLIDER         1062
#define IDC_RADIUS                      1062
#define IDC_ENTRYPOINT2                 1062
#define IDC_EXITPOINT                   1062
#define IDC_TEXEL_SIZE_SLIDER           1062
#define IDC_SLIDER2                     1063
#define IDC_DISTANCE                    1063
#define IDC_SLOPE                       1063
#define ID_INSERT_SOUND                 1063
#define IDC_BRUSH_HEIGHT_SLIDER         1063
#define IDC_ANGLE_SLIDER                1063
#define IDC_NUM_DENSITY                 1064
#define IDC_BRUSH_HARDNESS_SLIDER       1064
#define IDC_NUM_DISTANCE                1065
#define IDC_SIZE2                       1065
#define IDC_NOISE_SCALE_SLIDER          1065
#define IDC_DENSITY2                    1066
#define IDC_NOISE_FREQ_SLIDER           1066
#define IDC_BRUSH_RADIUS_SLIDER2        1067
#define IDC_CONSOLE_OUTPUT              1070
#define IDC_SLOPE_START                 1073
#define IDC_SLOPE_END                   1074
#define IDC_PREVIEW                     1076
#define IDC_ALTITUDE_START              1078
#define IDC_ALTITUDE_END                1079
#define IDC_RECENT_MAPS                 1079
#define IDC_MAP_FILENAME                1080
#define IDC_BROWSE_FOR_MAP              1081
#define IDC_CHANGE_LEV_DIR              1082
#define IDC_DIR_NAME                    1083
#define IDC_OBJ_DESCRIPTION             1089
#define IDC_OBJ_PREVIEW                 1090
#define IDC_TTS_HOLD                    1091
#define IDC_TTS_FETCH                   1092
#define IDC_OBJECTS                     1094
#define IDC_SEL_ALL                     1095
#define IDC_SEL_NONE                    1096
#define IDC_SEL_INV                     1097
#define IDC_HEIGHT_SLIDER               1099
#define IDC_HEIGHT_STATIC               1100
#define IDC_BASE                        1101
#define IDC_USE_LAYER                   1102
#define IDC_STAT_OBJ_IN_USE             1103
#define IDC_SHOW_TREES                  1105
#define IDC_SHOW_DIST_MAP               1106
#define IDC_CLEAR_DIST_MAP              1107
#define IDC_INVERT_DIST_MAP             1108
#define IDC_SHARE_DIST_MAP              1109
#define IDC_BRUSH_SIZE                  1110
#define IDC_STATIC_BRUSH_SIZE           1111
#define IDC_STATIC_OBJ                  1112
#define IDC_SLOPE_RANGE                 1113
#define IDC_STATIC_LABEL1               1114
#define IDC_STATIC_LABEL2               1115
#define IDC_STATIC_LABEL3               1116
#define IDC_STATIC_LABEL4               1117
#define IDC_STATIC_LABEL5               1118
#define IDC_CHANGE_CGF                  1119
#define IDC_BENDING                     1120
#define IDC_PLUGINS                     1120
#define IDC_STATIC_LABEL7               1120
#define IDC_STATIC_LABEL6               1121
#define IDC_BUTTON2                     1123
#define IDC_EDIT_SURFACETYPES           1123
#define IDC_EDIT_SHAPE                  1123
#define IDC_PHYSICS                     1123
#define IDC_SHADERTEMPL_CHOOSEFILE      1123
#define IDC_SHADERTEMPL_LOAD            1123
#define IDC_BROWSE_OBJECT               1123
#define IDC_TAB                         1124
#define IDC_HOLE_REMOVE                 1124
#define IDC_SHADERTEMPL_SAVE            1124
#define IDC_SYNCPLAYER                  1124
#define ID_EDIT_SELECT                  1125
#define IDC_SETTINGS_FRAME              1125
#define IDC_SHADERTEMPL_GETFROMSEL      1125
#define IDC_VIEW                        1126
#define IDC_SHADERTEMPL_SELECTBYSTP     1126
#define IDC_CLEAR                       1127
#define IDC_EDIT_HM                     1128
#define IDC_SUN_COLOR                   1128
#define IDC_DISTRIBUTE                  1128
#define IDC_SKY_COLOR                   1129
#define IDC_DISTRIBUTE2                 1129
#define IDC_DISTRIBUTE_MASK             1129
#define IDC_CLEAR_MASK                  1130
#define IDC_VIEW_WITH_TEXTURING         1135
#define ID_TERRAIN_NOISE                1136
#define ID_TERRAIN_SMOOTH               1137
#define ID_TERRAIN_SMOOTH2              1138
#define ID_TERRAIN_SMOOTH3              1139
#define ID_TERRAIN_SMOOTH4              1140
#define ID_TERRAIN_MAKEHOLE             1140
#define ID_TERRAIN_SMOOTH5              1141
#define IDC_ANIMFRAME                   1141
#define ID_TERRAIN_SMOOTH6              1142
#define IDC_OBJECT_NAME                 1142
#define ID_TERRAIN_SMOOTH7              1143
#define IDC_OBJECT_COLOR                1143
#define ID_TERRAIN_REMOVEHOLE           1144
#define IDC_NUMBER                      1149
#define IDC_POSY                        1151
#define IDC_POSZ                        1152
#define IDC_POSX                        1153
#define IDC_OBJECT_AREA                 1154
#define IDC_STATOBJ_RELOAD              1155
#define IDC_OBJECT_HELPER               1155
#define IDC_STATOBJ_NAME                1156
#define IDC_LIST_ENTITY                 1159
#define IDC_LIST_BUILDING               1160
#define IDC_LIST_TAGPOINT               1161
#define IDC_LIST_OTHER                  1162
#define IDC_LIST_STATOBJ                1163
#define IDC_LIST_SOUND                  1164
#define IDC_LIST_PREFABS                1164
#define IDC_FASTFIND                    1165
#define IDC_LIST_GROUPS                 1166
#define IDC_LIST_VOLUMES                1167
#define IDC_LIST_PATHS                  1168
#define IDC_LIST_BRUSHES                1169
#define IDC_LIST_AIPOINTS               1170
#define IDC_SOBJ_SIZE                   1173
#define IDC_SOBJ_DENSITY                1174
#define IDC_SOBJ_BENDING                1175
#define IDC_SOBJ_SLOPEEND               1176
#define IDC_SOBJ_SLOPESTART             1177
#define IDC_SOBJ_ALTSTART               1178
#define IDC_SOBJ_SLOPERANGE             1179
#define IDC_SOBJ_ALTEND                 1180
#define IDC_OBJECTS_FRAME               1181
#define IDC_SOBJ_SIZEVAR                1181
#define IDC_PROP                        1182
#define IDC_STATIC_DISTRIB              1184
#define IDC_STAT_OBJ_LIST               1185
#define IDC_LIST2                       1190
#define IDC_INFO_WH                     1192
#define IDC_VECTOR_LOCK                 1193
#define IDC_ANIMATE_LIGHTS              1194
#define IDC_DISABLE_LOD                 1195
#define IDC_SUNCOLOR_SCALE              1197
#define IDC_INFO_TEXT                   1199
#define IDC_VERSION                     1200
#define IDC_EDIT_FORMULA_PARAM1         1202
#define IDC_EDIT_FORMULA_PARAM2         1203
#define IDC_AUTO_GEN_MASK               1203
#define IDC_EDIT_FORMULA_PARAM3         1204
#define IDC_LOAD_MASK                   1204
#define IDC_EXPORT_MASK                 1206
#define IDC_SURFACE_TYPES               1210
#define IDC_SFTYPE_DETAILTEXTURE        1211
#define IDC_DETAIL_OBJECTS              1212
#define IDC_SURFACE_TYPE                1213
#define IDC_SFTYPE_BROWSE_BUMPMAP       1213
#define IDC_SFTYPE_DETAILTEXTURE_TEXT   1214
#define IDC_BROWSER_TREE                1215
#define IDC_SFTYPE_DETAILTEXTURE_TEXT2  1215
#define IDC_SFTYPE_BUMPMAP_TEXT         1215
#define IDC_NUM_FILES                   1216
#define IDC_SFTYPE_MATERIAL             1217
#define IDC_MATERIAL                    1217
#define IDC_LIST1                       1227
#define IDC_UNDO                        1227
#define IDC_HIDDEN_SECTORS              1227
#define IDC_ANIMATIONS                  1227
#define IDC_USED                        1227
#define IDC_ENTITIES                    1227
#define IDC_LAYERS                      1227
#define IDC_LAYOUTS                     1227
#define IDC_PRESETS                     1227
#define IDC_ANCHORS                     1227
#define IDC_AVAILABLE                   1228
#define IDC_EVENTS                      1228
#define IDC_SOUNDS                      1228
#define IDC_SOBJ_CASTSHADOW             1230
#define IDC_FLATTEN                     1231
#define IDC_HIDE_ALL                    1232
#define IDC_HIDE_NONE                   1233
#define IDC_HIDE_INVERT                 1234
#define IDC_HIDE_ENTITY                 1235
#define IDC_HIDE_BUILDING               1236
#define IDC_HIDE_PREFABS                1236
#define IDC_HIDE_TAGPOINT               1237
#define IDC_HIDE_STATOBJ                1238
#define IDC_HIDE_AIPOINT                1238
#define IDC_HIDE_SOUND                  1239
#define IDC_HIDE_GROUP                  1240
#define IDC_HIDE_LABELS                 1241
#define IDC_HIDE_VOLUME                 1242
#define IDC_LENGTH                      1242
#define IDC_HIDE_PATH                   1243
#define IDC_WIDTH                       1243
#define IDC_PROPERTIES                  1243
#define IDC_DISPLAY_BBOX                1243
#define IDC_HEIGHT                      1244
#define IDC_DISPLAY_INDOORS             1244
#define IDC_HIDE_PATH2                  1244
#define IDC_HIDE_BRUSH                  1244
#define IDC_DISPLAY_STATICOBJ           1245
#define IDC_DISPLAY_LIVINGOBJ           1246
#define IDC_DISPLAY_DEBUG_LIGHTS        1246
#define IDC_DISPLAY_FOG                 1247
#define IDC_DISPLAY_DECALS              1248
#define IDC_DISPLAY_SKYBOX              1249
#define IDC_DISPLAY_TERRAIN             1250
#define IDC_DISPLAY_WATER               1251
#define IDC_DISPLAY_BEACHES             1252
#define IDC_DISPLAY_SHADOWMAPS          1253
#define IDC_DISPLAY_DETAILTEX           1254
#define IDC_DISPLAY_DETAILOBJ           1255
#define IDC_DISPLAY_RAIN                1256
#define IDC_DISPLAY_RADIUSES            1256
#define IDC_DISPLAY_ALL                 1257
#define IDC_DISPLAY_NONE                1258
#define IDC_DISPLAY_INVERT              1259
#define IDC_DISPLAY_FARTERRAIN          1260
#define IDC_DISPLAY_PARTICLES           1260
#define IDC_SHADERS                     1261
#define IDC_DISPLAY_PROFILE             1261
#define IDC_HIDE                        1262
#define IDC_DISPLAY_AIDEBUGDRAW         1262
#define IDC_FREEZE                      1263
#define IDC_ADD                         1263
#define IDC_BRUSH_ADD                   1263
#define IDC_MEM_INFO                    1263
#define IDC_NEW_CATEGORY                1263
#define IDC_EDITSCRIPT                  1264
#define IDC_BRUSH_REMOVE                1264
#define IDC_RENAME                      1264
#define IDC_MEM_INFO2                   1264
#define IDC_DISPLAY_RADIUSES2           1264
#define IDC_ENABLE_PREVIEW              1264
#define IDC_METHODS                     1265
#define IDC_BRUSH_CLONE                 1265
#define IDC_ADD2                        1265
#define IDC_REFRESH                     1265
#define IDC_HIDE_HELPERS                1265
#define IDC_RELOADSCRIPT                1266
#define IDC_BRUSH_RENAME                1266
#define IDC_MEM_STATS                   1266
#define IDC_ADD_METHOD                  1267
#define IDC_BRUSH_HIDE                  1267
#define IDC_TEXMEM_STATS                1267
#define IDC_GOTO_METHOD                 1268
#define IDC_BRUSH_UNHIDE                1268
#define IDC_DISPLAY_PHYSICSDEBUGDRAW    1268
#define IDC_RUN_METHOD                  1269
#define IDC_OBJECT_ADD                  1269
#define IDC_DISPLAY_PROFILERENDERER     1269
#define IDC_MISSIONS                    1270
#define IDC_PROTOTYPE                   1270
#define IDC_DISPLAY_PROFILESHADERS      1270
#define IDC_DESCRIPTION                 1271
#define IDC_PROTOTYPE2                  1271
#define IDC_GETPHYSICS                  1271
#define IDC_DISPLAY_OVERDRAW            1271
#define IDC_DISPLAY_PROFILESHADERS3     1272
#define IDC_DISPLAY_RENDERERRESOURCES   1272
#define IDC_SHARED                      1273
#define IDC_GETPHYSICS2                 1273
#define IDC_RESETPHYSICS                1273
#define IDC_EVENT                       1274
#define IDC_DISPLAY_PROFILE2            1274
#define IDC_EVENT_TARGETS               1275
#define IDC_ANIMATION                   1275
#define IDC_EVENT_REMOVE                1277
#define IDC_EVENT_SEND                  1278
#define IDC_EVENT_ADD                   1281
#define IDC_EVENT_ADD2                  1282
#define IDC_EVENT_ADDMISSION            1282
#define ID_LOCK_SELECTION               1289
#define IDC_EVENTTREE                   1293
#define IDC_BRUSH_RADIUS                1297
#define IDC_BRUSH_HEIGHT                1298
#define IDC_BRUSH_TYPE                  1299
#define IDC_BRUSH_NOISE                 1300
#define IDC_BUILDING                    1301
#define IDC_BRUSH_HARDNESS              1301
#define IDC_CHANGE                      1302
#define IDC_NOISE_SCALE                 1302
#define IDC_MODIFY                      1303
#define IDC_NOISE_FREQ                  1303
#define IDC_HOLE                        1304
#define IDC_BRUSH_RADIUS2               1304
#define IDC_VEGETATION                  1305
#define IDC_ENVIRONMENT                 1306
#define IDC_SHADER                      1307
#define IDC_DISABLE_SHADOW              1308
#define IDC_TEXTURE                     1308
#define IDC_CAST_SHADOW                 1308
#define IDC_VERTEX_LIGHTING             1309
#define IDC_RECV_SHADOW                 1309
#define IDC_CAST_SHADOW2                1309
#define IDC_TEXTURE2                    1309
#define IDC_TERRAIN_MOVE                1309
#define IDC_REPOSITION_OBJECTS          1310
#define IDC_RIGID_BODY                  1310
#define IDC_BUTTON1                     1311
#define IDC_RELOAD                      1311
#define IDC_SPAWN                       1311
#define IDC_SELECT_ALL                  1311
#define IDC_UNDO_BUTTON                 1311
#define IDC_SHADERTEMPLATE_CREATE       1311
#define IDC_APPLY                       1311
#define IDC_CANCEL                      1311
#define IDC_PICK                        1311
#define IDC_NEW                         1311
#define IDC_SHADERTEMPL_COPY            1311
#define IDC_WEAPONMODEL                 1311
#define IDC_RESCALE_TIME                1311
#define IDC_EQUIPPACKADDBTN             1311
#define IDC_BROWSE                      1311
#define IDC_FILENAME                    1311
#define IDC_BROWSE_PREFAB               1311
#define IDC_RESETSIZE                   1311
#define IDC_BROWSE_EXE                  1311
#define IDC_SELECT_PROPERTY_VALUE       1311
#define IDC_BUTTON3                     1312
#define IDC_PICK_COLOR                  1312
#define IDC_SELECT_NONE                 1312
#define IDC_BIND                        1312
#define IDC_UNDO_CLEAR                  1312
#define IDC_SELECT                      1312
#define IDC_SHADERTEMPL_PASTE           1312
#define IDC_HIDABLE                     1312
#define IDC_EQUIPPACKDELBTN             1312
#define IDC_STOPANIMATION               1312
#define IDC_BROWSEMUSIC                 1312
#define IDC_RESETSIZE3                  1312
#define IDC_BROWSE_DATABASE             1312
#define IDC_SELECT_PROPERTY_NAME        1312
#define IDC_BUTTON4                     1313
#define IDC_INNER_RADIUS                1313
#define IDC_SELECT_INVERT               1313
#define IDC_UNBIND                      1313
#define IDC_SHADERTEMPL_PASTE2          1313
#define IDC_SHADERTEMPL_SETDEFAULT      1313
#define IDC_PRECALC_SHADOW2             1313
#define IDC_RESETSIZE2                  1313
#define IDC_BROWSE_FILE                 1313
#define IDC_BUTTON5                     1314
#define IDC_OUTER_RADIUS                1314
#define IDC_SHADERTEMPL_TOLIB           1314
#define IDC_RELOAD_FILE                 1314
#define IDC_VOLUME                      1315
#define IDC_HELPERS                     1315
#define IDC_SHADERTEMPL_TOLIB2          1315
#define IDC_SHADERTEMPL_FROMLIB         1315
#define IDC_DETACH                      1315
#define IDC_VOLUME2                     1316
#define IDC_PAN                         1316
#define IDC_BROWSESOUND                 1316
#define IDC_DETACHALL                   1316
#define IDC_PAN2                        1317
#define IDC_BLENDOUT                    1317
#define IDC_STOPANIMATION2              1317
#define IDC_INRADIUS                    1317
#define IDC_AMP                         1318
#define IDC_OUTRADIUS                   1318
#define IDC_MOVE_SPEED                  1320
#define IDC_WIREFRAME                   1324
#define IDC_PORTALS                     1325
#define IDC_LOOP                        1326
#define IDC_GRID                        1327
#define IDC_LOOP2                       1327
#define IDC_SYNCHRONIZE_PHASE           1327
#define IDC_UNLOAD                      1327
#define IDC_NORMALS                     1328
#define IDC_SHIFTX                      1333
#define IDC_SHIFTY                      1334
#define IDC_SCALEX                      1335
#define IDC_PROGRESS                    1335
#define IDC_PRECALC_SHADOW              1336
#define IDC_SCALEY                      1336
#define IDC_INFO                        1336
#define IDC_ROTATE                      1337
#define IDC_LAYER                       1337
#define IDC_TWIN                        1338
#define IDC_BLENDTIME                   1339
#define IDC_BLENDINTIME                 1339
#define IDC_BRUSHES                     1340
#define IDC_BLENDOUTTIME                1340
#define IDC_HEIGHT_MIN                  1341
#define IDC_HEIGHT_MAX                  1342
#define IDC_BRUSH_DENSITY               1343
#define IDC_CLONE                       1344
#define IDC_SLOPE_MIN                   1345
#define IDC_SLOPE_MAX                   1346
#define IDC_ENTITY                      1346
#define IDC_AREA_ID                     1347
#define IDC_NUM_POINTS                  1348
#define IDC_CLOSED                      1349
#define IDC_AMMUNITION                  1351
#define ID_TERRAIN_COLLISION            1352
#define IDC_TERRAIN_COLLISION           1353
#define IDC_SNAPTOGRID                  1354
#define IDC_BEHAVIOR                    1364
#define IDC_MAP_VISIBLE                 1366
#define IDC_LAYER_NAME                  1374
#define IDC_SHADERTEMPL_XML             1376
#define IDC_COMBO1                      1377
#define IDC_TEMPLATECOMBO               1377
#define IDC_PROJECTION                  1377
#define IDC_TERRAIN_RESOLUTION          1377
#define IDC_SIDES                       1377
#define IDC_LM_RESOLUTION               1377
#define IDC_TERRANI_UNITS               1378
#define IDC_SHADERTEMPL_MATERIALNAME    1379
#define IDC_EDIT1                       1381
#define IDC_SHADERTEMPL_FILENAME        1381
#define IDC_MASS                        1381
#define IDC_NAME                        1381
#define IDC_SCRIPT                      1381
#define IDC_GRID_SIZE                   1381
#define IDC_BLEND_TIME                  1381
#define IDC_OBJECT                      1381
#define IDC_ALT_START                   1381
#define IDC_PREVNEXT                    1382
#define IDC_SHADERTEMPL_NAME            1382
#define IDC_GRID_SCALE                  1382
#define IDC_BONE                        1382
#define IDC_ALT_END                     1382
#define IDC_MUSICSCRIPT                 1382
#define IDC_TIME_SCALE                  1382
#define IDC_EXE                         1382
#define IDC_XVALUE                      1383
#define IDC_DATABASE                    1383
#define IDC_CLASS                       1383
#define IDC_YVALUE                      1384
#define IDC_ANGLESNAP_SIZE              1384
#define IDC_PROJECT                     1384
#define IDC_CLASS2                      1384
#define IDC_TYPE                        1384
#define IDC_ZVALUE                      1385
#define IDC_WVALUE                      1386
#define IDC_TIME                        1387
#define IDC_EASETO                      1388
#define IDC_KEYNUM                      1389
#define IDC_TCBPREVIEW                  1390
#define IDC_TENSION                     1391
#define IDC_NODES                       1391
#define IDC_CONTINUITY                  1392
#define IDC_BIAS                        1393
#define IDC_START_TIME                  1393
#define IDC_END_TIME                    1394
#define IDC_EASEFROM                    1395
#define IDC_ALWAYS_PLAY                 1395
#define IDC_ALWAYS_PLAY2                1396
#define IDC_CUT_SCENE                   1396
#define IDC_KEY                         1397
#define IDC_EQUIPPACKCOMBO              1399
#define IDC_EQUIPPACK                   1399
#define IDC_EQUIPAVAILLST               1400
#define IDC_EQUIPUSEDLST                1401
#define IDC_EQUIPADDBTN                 1402
#define IDC_INSERT                      1402
#define IDC_EQUIPDELBTN                 1403
#define IDC_EQUIPAMMOPROP               1404
#define IDC_CREATE                      1406
#define IDC_USE_TERRAIN                 1407
#define IDC_CREATE2                     1407
#define IDC_NOMUSIC                     1407
#define IDC_TERRAIN_INFO                1408
#define IDC_LEVEL                       1409
#define IDC_ID                          1410
#define IDC_SNAP                        1411
#define IDC_SNAPANGLE                   1411
#define IDC_ANGLESNAP                   1412
#define IDC_OBJECT_CLONE                1413
#define IDC_OBJECT_REPLACE              1414
#define IDC_OBJECT_REMOVE               1415
#define IDC_DISABLEHUD                  1418
#define IDC_DISABLEPLAYER               1419
#define IDC_DISABLEPHYICS               1420
#define IDC_DISABLEPLAYER2              1421
#define IDC_DISABLEAI                   1421
#define IDC_DISABLEPLAYER3              1422
#define IDC_16TO9                       1422
#define IDC_TAB2                        1422
#define IDC_CHECK1                      1423
#define IDC_TOGGLEVARONOFF              1423
#define IDC_LOCKBLENDTIMES              1423
#define IDC_CHECK_SHADOWS               1423
#define IDC_DISABLESOUNDS               1423
#define IDC_PREFAB                      1424
#define IDC_CHECK_AVERAGING             1424
#define IDC_TREE1                       1425
#define IDC_EXTERNAL                    1425
#define IDC_TREE                        1426
#define IDC_TEXT                        1427
#define IDC_LINE                        1428
#define IDC_MATERIAL_BROWSE             1429
#define IDC_MATERIAL_BROWSE2            1430
#define IDC_MATERIAL_RESET              1430
#define IDC_HOLD                        1431
#define IDC_BLENDIN                     1432
#define IDC_STATIC2                     1433
#define IDC_STATIC3                     1434
#define IDC_DBG_OUTPUT_OBJ              1435
#define IDC_DBG_BORDERS                 1436
#define IDC_CHECK4                      1437
#define IDC_LOW_QUALITY_MODE            1437
#define IDC_DONT_MERGE_POLYS            1437
#define IDC_LOW_QUALITY_MODE2           1438
#define IDC_COMPILER_OUTPUT             1439
#define IDC_PLAYING                     1440
#define IDC_RECOMPUTE_SEL_ONLY          1441
#define IDC_PARAMS                      1442
#define IDC_STREAMING                   1443
#define IDC_STREAMING2                  1444
#define IDC_THEME                       1444
#define IDC_MOOD                        1445
#define IDC_PLAYINGFRAME                1446
#define ID_RECOMPILE_ALL                1447
#define IDC_CHECK2                      1448
#define ID_RECOMPILE_ALL2               1448
#define ID_RECOMPILE_LIGHTS             1448
#define IDC_USE_SUN_LIGHT               1449
#define IDC_HEMISAMPLEQ                 1450
#define IDC_USE_SUN_LIGHT2              1450
#define IDOK1                           1451
#define IDC_AUTOSELECT                  1452
#define IDC_PAINTVEGETATION             1453
#define IDC_PAINT_SIMPLELIGHTING        1454
#define IDC_TEXEL_SIZE                  1455
#define IDC_PAINT_TERRAIN_SHADOWS       1455
#define IDC_COMBO3                      1456
#define IDC_SUB_SAMPLING                1456
#define IDC_USERNAME                    1456
#define IDC_PAINT_OBJECT_SHADOWS        1456
#define IDC_ERRORS                      1457
#define IDC_SUB_SAMPLING2               1457
#define IDC_DXT_SOFT                    1457
#define IDC_OCCLUSION                   1457
#define IDC_INFOTEXT                    1458
#define IDC_OCCLUSION2                  1458
#define IDC_HDR                         1458
#define IDC_LABELS_DISTANCE             1459
#define IDC_HEMISPHERE                  1460
#define IDC_DP3                         1461
#define IDC_PRECISELIGHTING2            1462
#define IDC_HTMLVIEW                    1464
#define IDC_PREVIEW_ON                  1468
#define IDC_STATIC_FILENAME             1469
#define IDC_STATIC_FILESTYPE            1470
#define IDC_STATIC_FILESYPE             1470
#define IDC_PROPERTY                    1471
#define IDC_PROPERTY_STATIC             1472
#define IDC_REMOVESUBMESH               1473
#define IDC_ADDSUBMESH                  1474
#define IDC_REMOVESUBMESH2              1475
#define IDC_RELOADSUBMESH               1475
#define IDC_CHANGESUBMESH               1476
#define IDC_MODELVIEW_SUBMESH_PANEL     1477
#define IDC_SUBMESH_VISIBLE             1478
#define IDC_RESETANIMATIONS             1479
#define IDC_LM_GEN_PROGRESS             1480
#define IDC_NUM_OBJECTS                 1481
#define IDC_LM_MEMUSAGE                 1481
#define IDC_EXTRACT_SELECTED            1482
#define IDC_EXTRACT_ALL                 1483
#define IDC_OBJECT_INFO                 1484
#define IDC_STREAM                      1485
#define IDC_SMOOTH_NORMALS              1486
#define IDC_SPOTASPOINT                 1487
#define IDC_STATIC_MEMUSAGE             1488
#define IDC_STATIC_MEMUSAGE2            1489
#define IDC_STATIC_METHODS_FRAME        1500
#define IDC_EDIT_BRUSHNAME              1501
#define IDC_EDIT_BRUSHTYPE              1502
#define IDC_ANGLE                       1503
#define IDC_FRAME                       1505
#define IDC_BOTTOM_FRAME                1505
#define IDC_CHECK_ERROR_LOG             1506
#define IDC_FILTER                      1507
#define ID_EDIT_SELECTALL               32773
#define ID_EDIT_SELECTNONE              32774
#define ID_ANIM_FAST_BACK               32781
#define ID_ANIM_BACK                    32782
#define ID_ANIM_PLAY                    32783
#define ID_ANIM_FRONT                   32784
#define ID_ANIM_FAST_FORWARD            32785
#define IDR_KEYFRAMES                   32787
#define ID_BUTTON32794                  32794
#define ID_BUTTON32795                  32795
#define ID_BUTTON32796                  32796
#define ID_BUTTON32797                  32797
#define ID_BUTTON32798                  32798
#define ID_VIEWOPTIONS_WIREFRAME        32799
#define ID_VIEWOPTIONS_FLATSHADED       32800
#define ID_VIEWOPTIONS_SMOOTHSHADED     32801
#define ID_VIEWOPTIONS_TEXTURED         32802
#define ID_TARGET_SPOTLIGHT             32803
#define ID_FREE_SPOTLIGHT               32804
#define ID_OMNI_LIGHT                   32805
#define ID_DIRECTIONAL_LIGHT            32806
#define ID_SUNLIGHT                     32807
#define ID_BUTTON32808                  32808
#define ID_BUTTON32809                  32809
#define ID_BUTTON32810                  32810
#define ID_BUTTON32811                  32811
#define ID_BUTTON32812                  32812
#define ID_TEST                         32813
#define ID_BUTTON32814                  32814
#define ID_BUTTON32815                  32815
#define ID_BUTTON32818                  32818
#define ID_BUTTON32819                  32819
#define ID_BUTTON32820                  32820
#define ID_BUTTON32821                  32821
#define ID_BUTTON32822                  32822
#define ID_BUTTON32823                  32823
#define ID_BUTTON32824                  32824
#define ID_WIREFRAME                    32825
#define ID_VIEW_ANIMATIONTOOLBAR        32826
#define ID_VIEW_UTILITIESTOOLBAR        32827
#define ID_BUTTON32828                  32828
#define ID_BUTTON32825                  32829
#define ID_BUTTON32826                  32830
#define ID_TERRAIN_BRUSH                32831
#define ID_TERRAIN_LOWER                32834
#define ID_TERRAIN_RAISE                32835
#define ID_TERRAIN_ZOOM                 32836
#define ID_BRUSH_1                      32838
#define ID_BRUSH_2                      32839
#define ID_BRUSH_3                      32840
#define ID_BRUSH_4                      32841
#define ID_BRUSH_5                      32842
#define ID_BRUSH_6                      32843
#define ID_BRUSH_7                      32844
#define ID_BRUSH_8                      32845
#define ID_BRUSH_9                      32846
#define ID_BRUSH_10                     32848
#define ID_TERRAIN_SCROLL               32849
#define ID_TERRAIN_ERASE                32854
#define ID_TERRAIN_GENERATE             32855
#define ID_BRUSH_11                     32864
#define ID_BUTTON32867                  32867
#define ID_BUTTON32868                  32868
#define ID_BUTTON32869                  32869
#define ID_BUTTON32870                  32870
#define ID_BUTTON32871                  32871
#define ID_BUTTON32872                  32872
#define ID_BUTTON32873                  32873
#define ID_BUTTON32874                  32874
#define ID_SKY_CLOUDS                   32875
#define ID_SKY_FOG                      32876
#define ID_SKY_WEATHER                  32877
#define ID_SKY_NORTH                    32878
#define ID_SKY_EAST                     32879
#define ID_SKY_SOUTH                    32880
#define ID_SKY_WEST                     32881
#define ID_TERRAIN_LOAD                 32882
#define ID_TERRAIN_RESIZE               32883
#define ID_TERRAIN_INVERT               32884
#define ID_TERRAIN_RUBBER               32885
#define ID_FILE_EXPORTTOGAME            32886
#define ID_GENERATORS_LIGHTING          32887
#define ID_GENERATORS_STATICOBJECTS     32888
#define ID_GENERATORS_TEXTURE           32889
#define ID_TERRAIN_LIGHT                32891
#define ID_TERRAIN_SURFACE              32892
#define ID_ACCEL32893                   32893
#define ID_FILE_EXPORTHEIGHTMAP         32895
#define ID_FILE_EXPORTLARGEPREVIEW      32898
#define ID_PREVIEW_APPLYLIGHTING        32899
#define ID_PREVIEW_SHOWWATER            32900
#define ID_LAYER_SETWATERLEVEL          32901
#define ID_FILE_EXPORT                  32902
#define ID_FILE_IMPORT                  32903
#define ID_LAYER_EXPORTTEXTURE          32904
#define ID_VIEW_EDITORLOGFILE           32905
#define ID_LIGHTING_SUNLIGHTCOLOR       32906
#define IDC_SET_FOG_COLOR               32907
#define ID_MODIFY_MAKEISLE              32908
#define ID_MODIFY_FLATTEN_LIGHT         32909
#define ID_MODIFY_FLATTEN_HEAVY         32910
#define ID_MODIFY_SMOOTH                32911
#define ID_EDIT_HOLD                    32912
#define ID_EDIT_FETCH                   32913
#define ID_MODIFY_REMOVEWATER           32914
#define ID_MODIFY_SMOOTHSLOPE           32915
#define ID_HEIGHTMAP_SHOWLARGEPREVIEW   32916
#define ID_OPTIONS_SELECTDETAILTEXTURE  32917
#define ID_OPTIONS_SHOWDETAILTEXTURE    32918
#define ID_FILE_CREATEOPENLEVEL         32921
#define ID_FILE_IMPORTSETTINGS          32923
#define ID_FILE_EXPORTSETTINGS          32924
#define ID_MODIFY_SMOOTHBEACHESCOAST    32925
#define ID_FILE_MERGESETTINGS           32925
#define ID_FILE_EXPORTTOGAMENOSURFACETEXTURE 32926
#define ID_EDIT_INSERTOBJECT            32929
#define ID_VIEW_SWITCHTOGAME            32930
#define ID_INSERT_TAGPOINT              32931
#define ID_INSERT_BUILDING              32932
#define IDC_DELETE                      32933
#define ID_EDIT_DELETE                  32934
#define ID_MOVE_OBJECT                  32935
#define ID_SELECT_OBJECT                32936
#define ID_RENAME_OBJ                   32937
#define ID_SET_HEIGHT                   32938
#define ID_SCRIPT_COMPILESCRIPT         32939
#define ID_SCRIPT_EDITSCRIPT            32941
#define ID_SET_AREA                     32942
#define ID_OPTIONS_SETLAYERBLENDING     32943
#define ID_MODIFY_NOISE                 32944
#define ID_MODIFY_NORMALIZE             32945
#define ID_MODIFY_REDUCERANGE           32946
#define ID_MODIFY_REDUCERANGELIGHT      32947
#define ID_MODIFY_RANDOMIZE             32948
#define ID_LOW_OPACITY                  32949
#define ID_MEDIUM_OPACITY               32950
#define ID_HIGH_OPACITY                 32951
#define ID_HOLD                         32953
#define ID_FETCH                        32954
#define ID_BUTTON32956                  32956
#define ID_OPTIONS_SHOWWATER            32957
#define ID_OPTIONS_SHOWMAPOBJECTS       32958
#define ID_FILE_EXIT                    32959
#define ID_SET_TO_HEIGHT                32960
#define IDR_ANIM_SEQUENCES              32961
#define ID_INSERT_STATICOBJECT          32962
#define ID_NOISE_BRUSH                  32963
#define ID_NORMAL_BRUSH                 32964
#define ID_EDIT_EDITOBJECT              32965
#define ID_EDIT_INSERTOBJECTID_EDIT_INSERTOBJECTID_EDIT_SELECTOBJECT 32967
#define ID_TOOLS_EXPORTTERRAINASGEOMETRIE 32968
#define ID_OPTIONS_EDITTERRAINCURVE     32969
#define ID_VIEWMODE_MOVE                32973
#define ID_EDIT_MODE_MOVE               32976
#define ID_EDITMODE_ROTATE              32981
#define ID_EDITMODE_SCALE               32985
#define ID_EDITMODE_MOVE                32986
#define ID_EDITMODE_SELECT              32987
#define IDC_SELECTION                   32990
#define ID_SELECTION_DELETE             32991
#define ID_EDIT_ESCAPE                  32992
#define ID_OBJECTMODIFY_SETAREA         32993
#define ID_OBJECTMODIFY_SETHEIGHT       32994
#define ID_SELECTION_OK                 32995
#define ID_OBJECTMODIFY_FREEZE          32996
#define ID_OBJECTMODIFY_UNFREEZE        32997
#define ID_GAME_SWITCH                  32998
#define ID_EDITMODE_SELECTAREA          33000
#define ID_SELECT_AXIS_XY               33011
#define ID_SELECT_AXIS_X                33012
#define ID_SELECT_AXIS_Y                33013
#define ID_SELECT_AXIS_Z                33015
#define ID_UNDO                         33019
#define ID_EDIT_CLONE                   33020
#define ID_SETWATERLEVEL                33021
#define ID_EXPORT_TERRAIN_GEOM          33022
#define ID_SELECTION_SAVE               33026
#define ID_BUTTON33029                  33029
#define ID_SELECTION_LOAD               33030
#define ID_GROUP_MAKE                   33031
#define ID_GROUP_OPEN                   33032
#define ID_GROUP_CLOSE                  33033
#define ID_GROUP_ATTACH                 33034
#define ID_GROUP_DETACG                 33035
#define ID_GOTO_SELECTED                33036
#define ID_GROUP_DETACH                 33037
#define ID_GROUP_UNGROUP                33038
#define ID_LAYER_SETWATERCOLOR          33039
#define ID_MISSION_NEW                  33040
#define ID_MISSION_DELETE               33041
#define ID_MISSION_DUPLICATE            33042
#define ID_MISSION_SELECT               33043
#define ID_MISSION_PROPERTIES           33044
#define ID_MISSION_RENAME               33045
#define IDC_MISSION                     33047
#define ID_SHOW_TIPS                    33049
#define IDC_MISSION_TIME                33050
#define ID_EDIT_LEVELDATA               33051
#define ID_FILE_EDITEDITORINI           33052
#define ID_FILE_EDITLOGFILE             33053
#define ID_SELECT_AXIS_TERRAIN          33054
#define ID_PREFERENCES                  33055
#define ID_EDIT_SURFACETYPES            33056
#define ID_RELOAD_SCRIPTS               33057
#define ID_RELOAD_SHADERS               33058
#define ID_RELOAD_GEOMETRY              33059
#define ID_REDO                         33060
#define IDC_LAYER_CURRENT               33067
#define ID_LAYER_VISIBLE                33068
#define ID_LAYER_FROZEN                 33069
#define ID_LAYER_SELECT                 33073
#define ID_LAYER_CURRENT                33076
#define ID_SWITCH_PHYSICS               33078
#define ID_REF_COORDS_SYS               33081
#define ID_TV_ADDKEY                    33087
#define ID_TV_DELKEY                    33088
#define ID_TV_MOVEKEY                   33089
#define ID_TV_SLIDEKEY                  33090
#define ID_TV_SCALEKEY                  33091
#define ID_TV_SEQUENCE                  33092
#define ID_TV_ADD_SEQUENCE              33093
#define ID_TV_DEL_SEQUENCE              33095
#define ID_TV_EDIT_SEQUENCE             33096
#define ID_TV_RECORD                    33097
#define ID_TV_PLAY                      33098
#define ID_TV_STOP                      33099
#define ID_TV_PAUSE                     33100
#define ID_ADDNODE                      33102
#define ID_BUTTON33104                  33104
#define ID_EDITTOOL_LINK                33105
#define ID_EDITTOOL_UNLINK              33106
#define ID_BUTTON33107                  33107
#define ID_MISSION_RELOAD               33107
#define ID_MISSION_EDIT                 33108
#define ID_BUTTON33109                  33109
#define ID_ADDSCENETRACK                33109
#define ID_EDITMODE_SNAP                33111
#define ID_SNAP_TO_GRID                 33114
#define ID_TAG_LOC1                     33120
#define ID_TAG_LOC2                     33121
#define ID_TAG_LOC3                     33122
#define ID_TAG_LOC4                     33123
#define ID_TAG_LOC5                     33124
#define ID_TAG_LOC6                     33125
#define ID_TAG_LOC7                     33126
#define ID_TAG_LOC8                     33127
#define ID_TAG_LOC9                     33128
#define ID_TAG_LOC10                    33129
#define ID_TAG_LOC11                    33130
#define ID_TAG_LOC12                    33131
#define ID_GOTO_LOC1                    33133
#define ID_GOTO_LOC2                    33134
#define ID_GOTO_LOC3                    33135
#define ID_GOTO_LOC4                    33136
#define ID_GOTO_LOC5                    33137
#define ID_GOTO_LOC6                    33138
#define ID_GOTO_LOC7                    33139
#define ID_GOTO_LOC8                    33140
#define ID_GOTO_LOC9                    33141
#define ID_GOTO_LOC10                   33142
#define ID_GOTO_LOC11                   33143
#define ID_GOTO_LOC12                   33144
#define ID_TV_JUMPEND                   33146
#define ID_TV_JUMPSTART                 33147
#define ID_TV_PREVKEY                   33148
#define ID_TV_NEXTKEY                   33150
#define ID_TV_EXPORT_SEQUENCE           33151
#define ID_TV_IMPORT_SEQUENCE           33152
#define ID_OBJECTMODIFY_ALIGN           33155
#define ID_BUTTON33159                  33159
#define ID_TV_CURSORPOS                 33160
#define ID_LAYER_NAME                   33161
#define ID_PLAY_LOOP                    33164
#define ID_TV_COPYKEYS                  33336
#define ID_TV_PASTEKEYS                 33337
#define ID_TV_COPYPASTEKEYS             33338
#define ID_TERRAIN                      33339
#define ID_ADDPRESET                    33341
#define ID_DELPRESET                    33342
#define ID_ADDSOUND                     33343
#define ID_DELSOUND                     33344
#define ID_SAVE                         33345
#define ID_BUTTON33346                  33346
#define ID_BRUSH_TOOL                   33347
#define ID_OBJECTMODIFY_ALIGNTOGRID     33348
#define ID_DB_ADDLIB                    33352
#define ID_DB_DELLIB                    33353
#define ID_DB_LIBRARY                   33354
#define ID_DB_ADD                       33355
#define ID_DB_REMOVE                    33356
#define ID_BUTTON33357                  33357
#define ID_DB_RELOAD                    33357
#define ID_BUTTON33358                  33358
#define ID_DB_PLAY                      33358
#define IDC_SELECTION_MASK              33359
#define ID_DB_MTL_DRAWBOX               33360
#define ID_DB_MTL_DRAWSPHERE            33366
#define ID_DB_MTL_DRAWTEAPOT            33367
#define ID_BUTTON33368                  33368
#define ID_BUTTON33369                  33369
#define ID_DB_SAVE                      33371
#define ID_DB_MTL_ASSIGNTOSELECTION     33372
#define ID_DB_MTL_GETFROMSELECTION      33373
#define ID_DB_MTL_DRAWSELECTED          33374
#define ID_DB_MTL_ADDSUBMTL             33375
#define ID_DB_MTL_DELSUBMTL             33377
#define ID_BUTTON33379                  33379
#define ID_DB_DESCRIPTION               33379
#define ID_DB_MTL_PICK                  33380
#define ID_DB_MTL_RESETMATERIAL         33381
#define ID_DB_MTL_COPY                  33382
#define ID_DB_MTL_PASTE                 33383
#define ID_DB_MTL_GENCUBEMAP            33384
#define ID_DB_                          33386
#define ID_DB_ASSIGNTOSELECTION         33387
#define ID_GEN_LIGHTMAPS_SELECTED       33388
#define ID_BUTTON33389                  33389
#define ID_DB_DEL                       33390
#define ID_DB_RENAME                    33391
#define ID_DB_LOADLIB                   33392
#define ID_DB_COPY                      33393
#define ID_DB_PASTE                     33394
#define ID_DB_CUT                       33395
#define ID_DB_SELECTASSIGNEDOBJECTS     33396
#define ID_DB_EXPORTLIBRARY             33397
#define ID_DB_CLONE                     33398
#define ID_PANEL_LAYERS_NEW             33403
#define ID_PANEL_LAYERS_RENAME          33404
#define ID_PANEL_LAYERS_DELETE          33405
#define ID_PANEL_LAYERS_EXPORT          33406
#define ID_PANEL_LAYERS_IMPORT          33407
#define ID_PANEL_LAYERS_FREEZE          33408
#define ID_PANEL_LAYERS_UNFREEZE        33409
#define ID_PANEL_LAYERS_VISIBLE         33411
#define ID_PANEL_LAYERS_HIDE            33412
#define ID_PANEL_LAYERS_SHOW            33413
#define ID_PANEL_VEG_EXPORT             33414
#define ID_PANEL_VEG_IMPORT             33415
#define ID_PANEL_VEG_DISTRIBUTE         33416
#define ID_PANEL_VEG_SCALE              33417
#define ID_PANEL_VEG_ADD                33418
#define ID_PANEL_VEG_REMOVE             33419
#define ID_PANEL_VEG_CLEAR              33420
#define ID_PANEL_VEG_CLONE              33422
#define ID_PANEL_VEG_RENAME             33423
#define ID_PANEL_VEG_REPLACE            33424
#define ID_PANEL_VEG_ADDCATEGORY        33425
#define ID_SELECT_AXIS_SNAPTOALL        33428
#define ID_HELP_SAVE                    33438
#define ID_HELP_GET                     33439
#define ID_DB_STOP                      33443
#define ID_DB_MUSIC_LOADFROMLUA         33445
#define ID_BUTTON33447                  33447
#define ID_DB_MUSIC_RELOADFILES         33447
#define ID_TOOLS_PREFERENCES            33448
#define ID_EDIT_INVERTSELECTION         33449
#define ID_MODIFY_PREFABS               33450
#define ID_PREFABS_MAKEFROMSELECTION    33451
#define ID_PREFABS_REFRESHALL           33452
#define ID_TERRAIN_SEP                  33454
#define ID_TERRAIN_TOOLTERRAINMODIFY    33455
#define ID_TOOLTERRAINMODIFY_SMOOTH     33456
#define ID_TERRAINMODIFY_SMOOTH         33457
#define ID_TERRAIN_VEGETATION           33458
#define ID_TERRAIN_PAINTLAYERS          33459
#define ID_PROGRESSBAR_CANCEL           33459
#define ID_DYNHELP_INFO                 33461
#define ID_DISPLAY_SWITCHPERSPECTIVECAMERA 33462
#define ID_SWITCHCAMERA_DEFAULTCAMERA   33463
#define ID_SWITCHCAMERA_SEQUENCECAMERA  33464
#define ID_SWITCHCAMERA_SELECTEDCAMERA  33465
#define ID_TV_RECORD_AUTO               33466
#define ID_DISPLAY_AVIRECORDER          33467
#define ID_AVIRECORDER_STARTAVIRECORDING 33468
#define ID_AVIRECORDER_STOPAVIRECORDING 33469
#define ID_AVIRECORDER_PAUSEAVIRECORDING 33470
#define ID_AVIRECORDER_SELECTFILENAME   33471
#define ID_AVIRECORDER_OUTPUTFILENAME   33472
#define ID_BUTTON33477                  33477
#define ID_VIEW_MENUBAR                 59398
#define ID_VIEW_ROLLUPBAR               59412
#define ID_VIEW_CONSOLEWINDOW           59413
#define ID_VIEW_TRACKVIEW               59415
#define ID_VIEW_DATABASE                59417

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        501
#define _APS_NEXT_COMMAND_VALUE         33478
#define _APS_NEXT_CONTROL_VALUE         1508
#define _APS_NEXT_SYMED_VALUE           148
#endif
#endif
