//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by XTResource.rc

#define XT_IDB_BTN_BAR                  4500
#define XT_IDB_SCROLL_ARW               4501
#define XT_IDB_FONTTYPE                 4502
#define XT_IDB_BTN_OUT                  4503
#define XT_IDB_LIGHTBULB                4504
#define XT_IDB_LISTEDIT                 4505
#define XT_IDB_BTN_PRINT                4506
#define XT_IDB_CHECKLISTBOX             4507
#define XT_IDI_XTREME                   4508
#define XT_IDC_DRAGCOPY                 4509
#define XT_IDC_DRAGMOVE                 4510
#define XT_IDC_HAND                     4511
#define XT_IDC_HSPLITBAR                4512
#define XT_IDC_DRAGNONE                 4513
#define XT_IDC_VSPLITBAR                4514
#define XT_IDC_HANDNONE                 4515
#define XT_IDD_WINDOWLIST               4516
#define XT_IDD_CUSTPAGE4                4517
#define XT_IDD_CUSTPAGE5                4518
#define XT_IDM_POPUP                    4519
#define XT_IDR_TBAR_HDR                 4520
#define XT_IDR_TBAR_OUT                 4521
#define XT_IDR_TBAR_BLANK               4523
#define XT_IDR_TBAR_HEXEDIT             4524
#define XT_IDD_PREVIEW_TOOLBAR          4525
#define XT_IDD_TIPOFTHEDAY              4526
#define XT_IDD_CUSTPAGE1                4527
#define XT_IDD_CUSTPAGE2                4528
#define XT_IDD_CUSTPAGE3                4529
#define XT_IDD_NEWTOOLBAR               4530
#define XT_IDD_COLORSTANDARD            4531
#define XT_IDD_COLORCUSTOM              4532
#define XT_IDS_REG_KEY                  4533
#define XT_IDS_REG_WINPOS               4534
#define XT_IDS_REG_BARID                4535
#define XT_IDS_REG_SETTINGS             4536
#define XT_IDS_REG_BARPOS               4537
#define XT_IDS_REG_WNDPOS               4538
#define XT_IDS_REG_RECENTLIST           4539
#define XT_IDS_REG_ITEMID               4540
#define XT_IDS_REG_CBARID               4541
#define XT_IDS_REG_COLINFO              4542
#define XT_IDS_NAME                     4543
#define XT_IDS_SIZE                     4544
#define XT_IDS_CONTRACT                 4545
#define XT_IDS_TYPE                     4546
#define XT_IDS_MODIFIED                 4547
#define XT_IDS_INVALID_VER              4548
#define XT_IDS_COLOR_AUTO               4549
#define XT_IDS_COLOR_CUST               4550
#define XT_IDS_ENTRY                    4552
#define XT_IDS_SELDIR                   4555
#define XT_IDS_DOCKWND                  4556
#define XT_IDS_RES_ASSERT               4557
#define XT_IDS_TOOLBAR                  4558
#define XT_IDS_ERROR_BLANK              4559
#define XT_IDS_STATUSBAR                4560
#define XT_IDS_ERROR_EXISTS             4561
#define XT_IDS_ERROR_LIMIT              4562
#define XT_IDS_CUSTOM_BAR               4563
#define XT_IDS_CUSTOM_CONFIRM           4564
#define XT_IDS_DOT                      4565
#define XT_IDS_NOHELPTOPIC              4566
#define XT_IDS_DEFEXT                   4567
#define XT_IDS_DEFFILT                  4568
#define XT_IDS_DEFTITLE                 4569
#define XT_IDS_CLICKKEEPOPEN            4570
#define XT_IDS_SE_0                     4571
#define XT_IDS_SE_ERR_FNF               4572
#define XT_IDS_SE_ERR_PNF               4573
#define XT_IDS_SE_ERR_ACCESSDENIED      4574
#define XT_IDS_SE_ERR_OOM               4575
#define XT_IDS_SE_ERR_BAD_FORMAT        4576
#define XT_IDS_SE_ERR_SHARE             4577
#define XT_IDS_SE_ERR_ASSOCINCOMPLETE   4578
#define XT_IDS_SE_ERR_DDETIMEOUT        4579
#define XT_IDS_SE_ERR_DDEFAIL           4580
#define XT_IDS_SE_ERR_DDEBUSY           4581
#define XT_IDS_SE_ERR_NOASSOC           4582
#define XT_IDS_SE_ERR_DLLNOTFOUND       4583
#define XT_IDS_SE_ERR_UNKOWN            4584
#define XT_IDS_CLOSE                    4585
#define XT_IDS_CLR_BLACK                4586
#define XT_IDS_CLR_BROWN                4587
#define XT_IDS_CLR_OLIVE_GREEN          4588
#define XT_IDS_CLR_DARK_GREEN           4589
#define XT_IDS_CLR_DARK_TEAL            4590
#define XT_IDS_CLR_DARK_BLUE            4591
#define XT_IDS_CLR_INDIGO               4592
#define XT_IDS_CLR_GRAY80               4593
#define XT_IDS_CLR_DARK_RED             4594
#define XT_IDS_CLR_ORANGE               4595
#define XT_IDS_CLR_DARK_YELLOW          4596
#define XT_IDS_CLR_GREEN                4597
#define XT_IDS_CLR_TEAL                 4598
#define XT_IDS_CLR_BLUE                 4599
#define XT_IDS_CLR_BLUEGRAY             4600
#define XT_IDS_CLR_GRAY50               4601
#define XT_IDS_CLR_RED                  4602
#define XT_IDS_CLR_LIGHTORANGE          4603
#define XT_IDS_CLR_LIME                 4604
#define XT_IDS_CLR_SEA_GREEN            4605
#define XT_IDS_CLR_AQUA                 4606
#define XT_IDS_CLR_LIGHT_BLUE           4607
#define XT_IDS_CLR_VIOLET               4608
#define XT_IDS_CLR_GRAY40               4609
#define XT_IDS_CLR_PINK                 4610
#define XT_IDS_CLR_GOLD                 4611
#define XT_IDS_CLR_YELLOW               4612
#define XT_IDS_CLR_BRIGHT_GREEN         4613
#define XT_IDS_CLR_TURQUOISE            4614
#define XT_IDS_CLR_SKY_BLUE             4615
#define XT_IDS_CLR_PLUM                 4616
#define XT_IDS_CLR_GRAY25               4617
#define XT_IDS_CLR_ROSE                 4618
#define XT_IDS_CLR_TAN                  4619
#define XT_IDS_CLR_LIGHT_YELLOW         4620
#define XT_IDS_CLR_LIGHT_GREEN          4621
#define XT_IDS_CLR_LIGHT_TURQUOISE      4622
#define XT_IDS_CLR_PALE_BLUE            4623
#define XT_IDS_CLR_LAVENDER             4624
#define XT_IDS_CLR_WHITE                4625
#define XT_IDS_CLR_GRAY                 4626
#define XT_IDS_CLR_MAROON               4627
#define XT_IDS_CLR_OLIVE                4628
#define XT_IDS_CLR_NAVY                 4629
#define XT_IDS_CLR_PURPLE               4630
#define XT_IDS_CLR_SILVER               4631
#define XT_IDS_CLR_FUCHSIA              4632
#define XT_IDS_CLR_NOFILL               4633
#define XT_IDS_CLR_NOFILL_TIP           4634
#define XT_IDS_AUTOMATIC                4635
#define XT_IDS_AUTOMATIC_TIP            4636
#define XT_IDS_MORE_COLORS              4637
#define XT_IDS_MORE_COLORS_TIP          4638
#define XT_IDS_STD_COLORS               4639
#define XT_IDS_TIPTEXT                  4640
#define XT_IDS_DIDYOUKNOW               4641
#define XT_IDS_FILE_ABSENT              4642
#define XT_IDS_FILE_CORRUPT             4643
#define XT_IDS_MENUBAR                  4644
#define XT_IDS_CONTROLBAR               4645
#define XT_IDS_CUSTOMIZE                4646
#define XT_IDS_COLOR_CAPTION            4647
#define XT_IDS_NEW                      4648
#define XT_IDS_CURRENT                  4649
#define XT_IDS_DIRECTORIES              4650
#define XT_IDS_FILES                    4651
#define XT_IDS_RESTORE                  4652
#define XT_IDS_WINDOWS                  4653
#define XT_IDS_MANAGEKEYBRD             4654
#define XT_IDS_COMMAND                  4655
#define XT_IDS_KEYS                     4656
#define XT_IDB_BTN_FRAME                4656
#define XT_IDS_DESCRIPTION              4657
#define XT_IDS_ALLCOMMANDS              4658
#define XT_IDS_REASSIGN                 4659
#define XT_IDS_WIND_MINIMIZE            4660
#define XT_IDS_WIND_RESTORE             4661
#define XT_IDS_WIND_CLOSE               4662
#define XT_IDS_TOOLBAR_OPTS             4663
#define XT_IDC_LBOX_TOOLSLIST           4664
#define XT_IDS_TOOLS                    4664
#define XT_IDC_EDIT_TOOLSCMD            4665
#define XT_IDS_PATH_INVALID             4665
#define XT_IDC_EDIT_TOOLSARG            4666
#define XT_IDS_AREYOUSURE               4666
#define XT_IDC_EDIT_TOOLSDIR            4667
#define XT_IDS_AREYOUSURE_2             4667
#define XT_IDC_TXT_TOOLSCMD             4668
#define XT_IDS_BROWSE                   4668
#define XT_IDC_TXT_TOOLSARG             4669
#define XT_IDS_BROWSE_FILTER            4669
#define XT_IDC_TXT_TOOLSDIR             4670
#define XT_IDS_MENU_CONTENTS            4670
#define XT_IDB_CHECKLISTBOX_3D          4672
#define XT_IDS_ANIM_SYSDEF              4672
#define XT_IDS_ANIM_RANDOM              4673
#define XT_IDS_ANIM_UNFOLD              4674
#define XT_IDS_ANIM_SLIDE               4675
#define XT_IDS_ANIM_FADE                4676
#define XT_IDR_PREVIEW_TOOLBAR          4677
#define XT_IDC_GROUP_EDIT               5501
#define XT_IDC_EDIT_TOOLBAR             5502
#define XT_IDC_LBOX_EDIT                5503
#define XT_IDC_LBOX_CHECK               5504
#define XT_IDC_LBOX_CATEGORIES          5505
#define XT_IDC_LBOX_COMMANDS            5506
#define XT_IDC_TXT_TOOLBARS             5507
#define XT_IDC_TXT_CATEGORIES           5508
#define XT_IDC_TXT_COMMANDS             5509
#define XT_IDC_TXT_SELECTED             5510
#define XT_IDC_BTN_CLOSE                5511
#define XT_IDC_BTN_EXPAND               5512
#define XT_IDC_BTN_LEFT                 5513
#define XT_IDC_BTN_RIGHT                5514
#define XT_IDC_BTN_HOME                 5515
#define XT_IDC_BTN_END                  5516
#define XT_IDC_BTN_NEW                  5517
#define XT_IDC_BTN_DELETE               5518
#define XT_IDC_BTN_UP                   5519
#define XT_IDC_BTN_DOWN                 5520
#define XT_IDC_BTN_BROWSE               5521
#define XT_IDC_BTN_DAYTIP_BORDER        5522
#define XT_IDC_CHK_DAYTIP_SHOW          5523
#define XT_IDC_BTN_DAYTIP_NEXT          5524
#define XT_IDC_BTN_RENAME               5525
#define XT_IDC_BTN_RESET                5526
#define XT_IDC_BTN_DESCRIPTION          5527
#define XT_IDC_CHK_STANDARD             5528
#define XT_IDC_CHK_MENUSHADOWS          5528
#define XT_IDC_CHK_RECENTMENU           5529
#define XT_IDC_CHK_SHOWFULL             5530
#define XT_IDC_EDIT_RED                 5531
#define XT_IDC_CHK_SCREENTIPS           5531
#define XT_IDC_TXT_COLORS               5532
#define XT_IDC_CHK_SHOWSHORTCUTKEYS     5532
#define XT_IDC_EDIT_GREEN               5533
#define XT_IDC_SPIN_HUE                 5534
#define XT_IDC_EDIT_LUM                 5535
#define XT_IDC_EDIT_SAT                 5536
#define XT_IDC_EDIT_HUE                 5537
#define XT_IDC_SPIN_SAT                 5538
#define XT_IDC_SPIN_LUM                 5539
#define XT_IDC_EDIT_BLUE                5540
#define XT_IDC_SPIN_RED                 5541
#define XT_IDC_SPIN_GREEN               5542
#define XT_IDC_SPIN_BLUE                5543
#define XT_IDC_TXT_HUE                  5544
#define XT_IDC_TXT_SAT                  5545
#define XT_IDC_TXT_LUM                  5546
#define XT_IDC_TXT_RED                  5547
#define XT_IDC_TXT_GREEN                5548
#define XT_IDC_TXT_BLUE                 5549
#define XT_IDC_CLR_WND                  5550
#define XT_IDC_CLR_LUM                  5551
#define XT_IDC_CLR_HEX                  5552
#define XT_IDC_LBOX_WINDOWS             5553
#define XT_IDC_BTN_CASCADE              5554
#define XT_IDC_BTN_MINIMIZE             5555
#define XT_IDC_BTN_CLOSEWINDOWS         5556
#define XT_IDC_BTN_SAVE                 5557
#define XT_IDC_BTN_TILEHORZ             5558
#define XT_IDC_BTN_TILEVERT             5559
#define XT_IDC_BTN_ACTIVATE             5560
#define XT_IDC_LBOX_ACCEL_COMMANDS      5561
#define XT_IDC_LBOX_KEYS                5562
#define XT_IDC_EDIT_SHORTCUTKEY         5564
#define XT_IDC_COMBO_CATEGORY           5565
#define XT_IDC_BTN_ASSIGN               5566
#define XT_IDC_BTN_ACCEL_RESET          5567
#define XT_IDC_BTN_REMOVE               5568
#define XT_IDC_TXT_NEWKEY               5570
#define XT_IDC_TXT_ASSIGNMENTS          5571
#define XT_IDC_TXT_FRAMETITLE           5572
#define XT_IDC_TXT_DESC_OVERVIEW        5573
#define XT_IDC_TXT_DESC_TITLE           5574
#define XT_IDC_CHK_VISUALIZE            5575
#define XT_IDC_TXT_PERSONALIZED         5576
#define XT_IDC_TXT_OTHER                5577
#define XT_IDC_SEP_PERSONALIZED         5578
#define XT_IDC_SEP_OTHER                5579
#define XT_IDC_COMBO_ANIMATION          5582
#define XT_IDC_SORTASC                  53773
#define XT_IDC_SORTDSC                  53774
#define XT_IDC_ALIGNLEFT                53775
#define XT_IDC_ALIGNCENTER              53776
#define XT_IDC_ALIGNRIGHT               53777
#define XT_IDC_LARGEICON                53778
#define XT_IDC_SMALLICON                53779
#define XT_IDC_REMOVEITEM               53780
#define XT_IDC_RENAMEITEM               53781
#define XT_IDC_CUSTOMIZE                53782
#define XT_IDC_CHEVRON                  53783
#define XT_IDC_REMOVEGROUP              53784
#define XT_IDC_RENAMEGROUP              53785
#define XT_IDC_BLANK                    53786
#define XT_IDC_SORT_CATEGORIZED         53787
#define XT_IDC_SORT_ALPHABETIC          53788
#define XT_IDC_TAB_CLOSE                53789

// Next default values for new objects

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4673
#define _APS_NEXT_COMMAND_VALUE         52790
#define _APS_NEXT_CONTROL_VALUE         5583
#define _APS_NEXT_SYMED_VALUE           4652
#endif
#endif
